Fix byte compilation errors
Fix the byte compilation errors:
In toplevel form:
ialign.el:42:1: Warning: defcustom for ‘ialign-minibuffer-keymap’ fails to
    specify type
ialign.el:126:1: Warning: Alias for ‘ialign-default-spacing’ should be
    declared before its referent

In end of data:
ialign.el:227:18: Warning: the function ‘rxt-pcre-to-elisp’ is not known to be
    defined.

By adding a type parameter the defcustom declaration of the keymap,
using defvaralias before defvar for ialign-initial-spacing and by
using noerror parameter of require along with featurep and fboundp to
handle pcre2el integration.